### ISSUE TITLE
Does not work in linux

### ISSUE THREAD

**Issue by layssi** [jonashaag/micromamba-pycharm#7]
~/micromamba-pycharm$ micromamba --version
1.5.1

./conda self-check
Traceback (most recent call last):
  File "./conda", line 98, in <module>
    sys.exit(main(args))
  File "./conda", line 47, in main
    micromamba(["--version"])
  File "./conda", line 25, in micromamba
    out = subprocess.check_output(["micromamba"] + cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'micromamba'

**Comment by jonashaag** [comment]
Thanks, you need to put Micromamba into your `$PATH`

**Comment by mxwell-dev** [comment]
@jonashaag this is possibly a bit more involved than initially thought. I have `$HOME/.local/bin` added to my path in `.profile`, `.bashrc` and `.zshrc` (the latter being my default shell). Because of this, self-check passes, but it seems that the PyCharm GUI ignores all of that somehow.
